In [ ]:
#Quiz16 ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

In [2]:
import numpy as np

temp=np.arange(1, 26)
arr = temp.reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [3]:
arr[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])