In [1]:
#Quiz13 ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14

In [24]:
import numpy as np

temp=np.arange(1, 26)
arr = temp.reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [25]:
arr[1:3,2:4]

array([[ 8,  9],
       [13, 14]])