In [ ]:
#Quiz18 จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5
#และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า 50 และปริ้นออกมา

In [2]:
import numpy as np

arr=np.random.randint(10, 101, (5,5))
print(arr)

[[ 57  54  56  93  65]
 [ 81  73  83  37  93]
 [100 100  16  84  59]
 [ 49  83  45  48  66]
 [ 92  12  14  91  29]]


In [4]:
print(arr[arr>50])

[ 57  54  56  93  65  81  73  83  93 100 100  84  59  83  66  92  91]
