In [1]:
#Quiz12 จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [14]:
import numpy as np

mtrx=np.random.randint(50, 101, (4,4))
print("Random Matrix = ")
print(mtrx)
print("Transpose of matrix = ")
print(mtrx.T)

Random Matrix = 
[[59 75 89 84]
 [71 58 88 64]
 [71 64 99 72]
 [63 70 91 63]]
Transpose of matrix = 
[[59 71 71 63]
 [75 58 64 70]
 [89 88 99 91]
 [84 64 72 63]]
