In [2]:
#Quiz17 จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

In [1]:
import numpy as np

arr=np.random.randint(10, 101, (5,5))
print(arr)

[[54 13 64 92 68]
 [19 93 23 23 90]
 [35 27 93 30 57]
 [51 59 48 65 24]
 [86 80 12 93 17]]
