In [ ]:
# Quiz20 เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 
#  นำเลข 9 ตัวนั้นมาทำเป็น matrix 3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

In [6]:
import numpy as np

count=0
x=np.zeros(9)
while (count<9):
    print("Please input integer number#{} [10,100]".format(count+1) )
    num = int(input())
    if (num >= 10 and num <=100):
        x[count]=num
        count+=1

print("x:")
print(x)

x_new = x.reshape(3,3)
print("Matrix x 3x3:")
print(x_new)

x_transpose = x_new.T
print("Matrix x transposed")
print(x_transpose)

Please input integer number#1 [10,100]
10
Please input integer number#2 [10,100]
20
Please input integer number#3 [10,100]
30
Please input integer number#4 [10,100]
40
Please input integer number#5 [10,100]
50
Please input integer number#6 [10,100]
60
Please input integer number#7 [10,100]
70
Please input integer number#8 [10,100]
80
Please input integer number#9 [10,100]
90
x:
[10. 20. 30. 40. 50. 60. 70. 80. 90.]
Matrix x 3x3:
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
Matrix x transposed
[[10. 40. 70.]
 [20. 50. 80.]
 [30. 60. 90.]]
