In [ ]:
# Quiz19 จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5
# และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่า มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

In [1]:
import numpy as np

arr=np.random.randint(10, 101, (5,5))
print(arr)

[[ 90  20  74  53  56]
 [ 81  62  13  79  96]
 [100  26  21  68  48]
 [ 45  63  94  32  58]
 [ 51  98  65  97  66]]


In [2]:
arr_new = arr[arr>40]
print(arr_new)

[ 90  74  53  56  81  62  79  96 100  68  48  45  63  94  58  51  98  65
  97  66]
